<?php

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */
/*
function feed_importer_field_widget_entity_reference_paragraphs_form_alter(&$element, FormStateInterface &$form_state, $context) {
    //vdp("Pasa por feed_importer_field_widget_entity_reference_paragraphs_form_alter");
    if ($element['#paragraph_type'] == 'alumno') {
        $element['subform']['field_text']['widget'][0]['#title'] = 'Altered title';
    }
}
*/
/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */
/*
function feed_importer_field_widget_paragraphs_form_alter(&$element, FormStateInterface &$form_state, $context) {
    //vdp("Pasa por feed_importer_field_widget_entity_reference_paragraphs_form_alter");
    if ($element['#paragraph_type'] == 'alumno') {
        $element['subform']['field_text']['widget'][0]['#title'] = 'Altered title';
    }
}
*/

function feed_importer_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    //vdp("Pasa por feed_importer_form_alter");
    //vdp($form['field_alumno']);
    //$form['order_fields:checkout']['#multilingual'] = FALSE;
    /*
    $form['order_fields:checkout']['field_alumno']['widget'][1] = $form['order_fields:checkout']['field_alumno']['widget'][0];
    $form['order_fields:checkout']['field_alumno']['widget'][1]['#delta'] = 1;
    $form['order_fields:checkout']['field_alumno']['#max_delta'] = 1;
    */
    //vdp($form['field_alumno']);
}

/*
function feed_importer_order_prepare_form(EntityInterface $entity, $operation, FormStateInterface $form_state) {
    $v1 = 1;
}

function feed_importer_commerce_order_prepare_form(EntityInterface $entity, $operation, FormStateInterface $form_state) {
    $v1 = 1;
}
*/

function feed_importer_order_pane_prepare_form(EntityInterface $entity, $operation, FormStateInterface $form_state) {
    $v1 = 1;
}

